@GeradorDocumentos.Api_HostAddress = http://localhost:5065

GET {{GeradorDocumentos.Api_HostAddress}}/weatherforecast/
Accept: application/json


###
POST {{GeradorDocumentos.Api_HostAddress}}/Documento/generate
Content-Type: application/json
Accept: application/pdf
{
  "nome": "Rafael Carlos",
  "documento": "12345678900",
  "valor": 150.75
}
